# Use the official Adminer image from Docker Hub
FROM adminer:latest

# Expose the port Adminer will run on
#EXPOSE 80
EXPOSE 8080 

# Start Adminer when the container is run
#CMD ["php", "-S", "0.0.0.0:80", "-t", "/var/www/html"]
#CMD ["php", "-S", "0.0.0.0:8080", "-t", "/var/www/html"]
